### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by dymbe**
Cleanup code. Also made it [PEP8](https://www.python.org/dev/peps/pep-0008/)-compliant

### CODE REVIEW

**Comment by dymbe** [comment]
Also removed the `__name__ == '__main__'` check inside the infinite while loop. Let me know if it was there for a reason

**Review by oyvinddenvik — APPROVED** [review]

**Review by oyvinddenvik — CHANGES_REQUESTED** [review]
Ros beginner tutorial states that the name check must be included.

**Comment by dymbe** [comment]
> Ros beginner tutorial states that the name check must be included.

It does not state that it has to be included, although it does use it in the code examples. The name-check only ensures that the code inside it does not run when the script is imported from another script. I do agree with you that it is good practice though, but it is kind of useless inside of a while loop. I will fix this by moving it outside of the while loop in my next commit

**Review by oyvinddenvik — APPROVED** [review]
I agree with the new changes.

**Pull request merged**
