### PR TITLE
Manta

### PR DESCRIPTION
**Pull request by ghese**
Several changes that should be on the master branch

### CODE REVIEW

**Comment by dymbe** [comment]
Some things will have to be changed
1. We should use another topic-name for the IMU-data. We have previously used /sensors/imu/data, but as we are planning on using multiple IMUs this year, we should use something like /sensors/imus/em7180/data.
2. It is unnecessary to include .pyc-files. All .pyc-files should be deleted from the repository, and a .gitignore-file should be added to the repository (that contains a line that says `*.pyc`)

You could also consider following the [PEP8](http://wiki.ros.org/PyStyleGuide) style guide in the future. 

**Other than that, good work!**

**Comment by ghese** [comment]
> Some things will have to be changed
> 
> 1. We should use another topic-name for the IMU-data. We have previously used /sensors/imu/data, but as we are planning on using multiple IMUs this year, we should use something like /sensors/imus/em7180/data.
> 2. It is unnecessary to include .pyc-files. All .pyc-files should be deleted from the repository, and a .gitignore-file should be added to the repository (that contains a line that says `*.pyc`)
> 
> You could also consider following the [PEP8](http://wiki.ros.org/PyStyleGuide) style guide in the future.
> 
> **Other than that, good work!**

This branch uses a topic name specifing the IMU name em7180. And there are no .pyc files in this branch.

**Comment by dymbe** [comment]
> > Some things will have to be changed
> > 
> > 1. We should use another topic-name for the IMU-data. We have previously used /sensors/imu/data, but as we are planning on using multiple IMUs this year, we should use something like /sensors/imus/em7180/data.
> > 2. It is unnecessary to include .pyc-files. All .pyc-files should be deleted from the repository, and a .gitignore-file should be added to the repository (that contains a line that says `*.pyc`)
> > 
> > You could also consider following the [PEP8](http://wiki.ros.org/PyStyleGuide) style guide in the future.
> > **Other than that, good work!**
> 
> This branch uses a topic name specifing the IMU name em7180. And there are no .pyc files in this branch.

The branch does use a topic name specifying the name of the IMU, but it does not follow the naming convention already used for topics in the controll-system, `/sensors/imus/em7180/data` is therefore more appropriate.

Regarding the .pyc-files: You are correct, my bad. You could consider adding them to gitignore anyways though, as it seems like the code generates a lot of them.

One more thing! Is there any reason for the nodes being anonymous? If not, i think it is preferable that they are not anonymous.

**Comment by ghese** [comment]
> > > Some things will have to be changed
> > > 
> > > 1. We should use another topic-name for the IMU-data. We have previously used /sensors/imu/data, but as we are planning on using multiple IMUs this year, we should use something like /sensors/imus/em7180/data.
> > > 2. It is unnecessary to include .pyc-files. All .pyc-files should be deleted from the repository, and a .gitignore-file should be added to the repository (that contains a line that says `*.pyc`)
> > > 
> > > You could also consider following the [PEP8](http://wiki.ros.org/PyStyleGuide) style guide in the future.
> > > **Other than that, good work!**
> > 
> > 
> > This branch uses a topic name specifing the IMU name em7180. And there are no .pyc files in this branch.
> 
> The branch does use a topic name specifying the name of the IMU, but it does not follow the naming convention already used for topics in the controll-system, `/sensors/imus/em7180/data` is therefore more appropriate.
> 
> Regarding the .pyc-files: You are correct, my bad. You could consider adding them to gitignore anyways though, as it seems like the code generates a lot of them.
> 
> One more thing! Is there any reason for the nodes being anonymous? If not, i think it is preferable that they are not anonymous.

Perhaps the Master branch should be more general purpose. While we keep the Manta branch specific to Manta. As in the topic structure you suggested to be a part of the manta branch, while the master branch can be useful to anyone else interested in using the IMU with ROS.

Will add the gitignore file as you mentioned.

I thought it was generally good practise to keep the nodes anonymous? Will fix that as well.

**Comment by ghese** [comment]
Evertyhing that was commented on, should be fixed now.

**Pull request merged**
